### ISSUE TITLE
Accuracy exception

### ISSUE THREAD

**Issue by Jambon1510** [goncalopp/simple-ocr-opencv#34]
**Context**
Hello 
I tried the below image
![passwordpad](https://user-images.githubusercontent.com/19289018/50382728-030b6f00-06e1-11e9-82d2-71f34e488ed3.png)

with Python 3

**current behavior**
When grounding via example_grounding.py the image above  then launching example.py by the same above image, I got below exception

```
Traceback (most recent call last):
  File "example_amundi.py", line 17, in <module>
    print("accuracy:", accuracy(test_image.ground.classes, test_classes))
  File "/mnt/Documents/jb/Dev/python/projects/moneygator/test/castor/ocr/simple-ocr-opencv-master/simpleocr/ocr.py", line 36, in accuracy
    raise Exception("expected " + str(expected.shape) + ", got " + str(result.shape))
Exception: expected (10, 1), got (18, 1)
```

**expected behavior**
it should not trigger the exception except if I am doing something bad (does that need more numbers for grounding?)

**Comment by goncalopp** [comment]
What that exception is telling you is that the number of recognized segments is different from the expected. In this case, it expected 10 segments from grounding (which makes sense for the image), but it detected 18 in the image. If you used the algorithm for the grounding (as opposed to manually calculating rectangles), then it's likely that it's due to different settings used when running both.

You can try to figure out what's happening by running with `show_steps=True` (see `example.py`)

**Comment by Jambon1510** [comment]
Ok got it thanks, I managed to make it work when I put any char on the 8 non number (q for example, I 
did put a space before and I had the description issue).

> accuracy: 1.0
> OCRed text:
>  32158qqqqqqqq70946


However it still not working whenever the image is different and the number are in a different place. Let me open another ticket for that
